name: Deploy Flask App

on:
  push:
    branches:
      - main  # Triggers deployment when code is pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add EC2 to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ec2-52-214-31-129.eu-west-1.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: Deploy Flask App to EC2
        run: |
          # SSH into EC2 instance and navigate to the flask-app directory
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@ec2-52-214-31-129.eu-west-1.compute.amazonaws.com "cd flask-app && docker-compose down && docker-compose up -d"
